[package]
name = "random-wallpaper"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
dirs = "5.0.0"
heck = "0.4.1"
notify-rust = "4.8.0"
rand_core = "0.6.4"
rand_distr = "0.4.3"
shellexpand = "3.1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-unwrap = "0.10.0"
